//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opus.Resources.Labels.Redaction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Redaction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Redaction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opus.Resources.Labels.Redaction.Redaction", typeof(Redaction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toteuta.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toteuta merkityt.
        /// </summary>
        public static string ExecuteApplyLabel {
            get {
                return ResourceManager.GetString("ExecuteApplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etsi ja hävitä.
        /// </summary>
        public static string ExecuteButton {
            get {
                return ResourceManager.GetString("ExecuteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suorita.
        /// </summary>
        public static string ExecuteCommandButton {
            get {
                return ResourceManager.GetString("ExecuteCommandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loppu.
        /// </summary>
        public static string RedactionEnd {
            get {
                return ResourceManager.GetString("RedactionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkitse alueet.
        /// </summary>
        public static string RedactionRange {
            get {
                return ResourceManager.GetString("RedactionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alku.
        /// </summary>
        public static string RedactionStart {
            get {
                return ResourceManager.GetString("RedactionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkitse sanat.
        /// </summary>
        public static string RedactionWords {
            get {
                return ResourceManager.GetString("RedactionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanat, jotka merkitään.
        /// </summary>
        public static string SearchWords {
            get {
                return ResourceManager.GetString("SearchWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erota pilkulla. Villit kortit * ja ? ovat sallittuja..
        /// </summary>
        public static string WordsHint {
            get {
                return ResourceManager.GetString("WordsHint", resourceCulture);
            }
        }
    }
}
