//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opus.Resources.ContextMenu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Arguments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Arguments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opus.Resources.ContextMenu.Arguments", typeof(Arguments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -compose.
        /// </summary>
        public static string Compose {
            get {
                return ResourceManager.GetString("Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -pdfa.
        /// </summary>
        public static string ConvertToPdfA {
            get {
                return ResourceManager.GetString("ConvertToPdfA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -extractdir.
        /// </summary>
        public static string ExtractDirectory {
            get {
                return ResourceManager.GetString("ExtractDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -extract.
        /// </summary>
        public static string ExtractFile {
            get {
                return ResourceManager.GetString("ExtractFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -workcopy.
        /// </summary>
        public static string WorkingCopy {
            get {
                return ResourceManager.GetString("WorkingCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -workcopyfolder.
        /// </summary>
        public static string WorkingCopyMultiple {
            get {
                return ResourceManager.GetString("WorkingCopyMultiple", resourceCulture);
            }
        }
    }
}
