//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opus.Resources.Labels.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExtractionOptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtractionOptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opus.Resources.Labels.Dialogs.ExtractionOptions", typeof(ExtractionOptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kysy aina erikseen.
        /// </summary>
        public static string AlwaysAskTitle {
            get {
                return ResourceManager.GetString("AlwaysAskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkinnät.
        /// </summary>
        public static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osien nimeäminen.
        /// </summary>
        public static string AskDialogTitle {
            get {
                return ResourceManager.GetString("AskDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakkaa zip-tiedostoon.
        /// </summary>
        public static string CreateZipTitle {
            get {
                return ResourceManager.GetString("CreateZipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pidä kaikki.
        /// </summary>
        public static string Keep {
            get {
                return ResourceManager.GetString("Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muotoile nimen malli.
        /// </summary>
        public static string NameHelper {
            get {
                return ResourceManager.GetString("NameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimen rakenne.
        /// </summary>
        public static string NameTemplate {
            get {
                return ResourceManager.GetString("NameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muunna pdf/a -muotoon.
        /// </summary>
        public static string PdfA {
            get {
                return ResourceManager.GetString("PdfA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poista kaikki.
        /// </summary>
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poista valitut.
        /// </summary>
        public static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiedoston nimi.
        /// </summary>
        public static string ZipDialogTitle {
            get {
                return ResourceManager.GetString("ZipDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakattavan tiedoston nimi.
        /// </summary>
        public static string ZipName {
            get {
                return ResourceManager.GetString("ZipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi sille yksittäiselle tiedostolle, joka zip-tiedoston sisään pakataan.
        /// </summary>
        public static string ZipNameHelper {
            get {
                return ResourceManager.GetString("ZipNameHelper", resourceCulture);
            }
        }
    }
}
