//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opus.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kieli.
        /// </summary>
        public static string HelpMenu_Language {
            get {
                return ResourceManager.GetString("HelpMenu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisenssit.
        /// </summary>
        public static string HelpMenu_Licenses {
            get {
                return ResourceManager.GetString("HelpMenu_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lähdekoodi.
        /// </summary>
        public static string HelpMenu_SourceCode {
            get {
                return ResourceManager.GetString("HelpMenu_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttöohje.
        /// </summary>
        public static string HelpMenu_UserManual {
            get {
                return ResourceManager.GetString("HelpMenu_UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englanti.
        /// </summary>
        public static string Language_en {
            get {
                return ResourceManager.GetString("Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suomi.
        /// </summary>
        public static string Language_fi {
            get {
                return ResourceManager.GetString("Language_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruotsi.
        /// </summary>
        public static string Language_sv {
            get {
                return ResourceManager.GetString("Language_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poista allekirjoituksia.
        /// </summary>
        public static string Title_Signature {
            get {
                return ResourceManager.GetString("Title_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erota kirjanmerkkejä.
        /// </summary>
        public static string Title_Split {
            get {
                return ResourceManager.GetString("Title_Split", resourceCulture);
            }
        }
    }
}
