//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opus.Resources.Operations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PhaseNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PhaseNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opus.Resources.Operations.PhaseNames", typeof(PhaseNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisätään kirjanmerkkejä....
        /// </summary>
        public static string AddingBookmarks {
            get {
                return ResourceManager.GetString("AddingBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisätään sivunumeroita....
        /// </summary>
        public static string AddingPageNumbers {
            get {
                return ResourceManager.GetString("AddingPageNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallennussijainnin valinta....
        /// </summary>
        public static string ChoosingDestination {
            get {
                return ResourceManager.GetString("ChoosingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muunnetaan tiedostoja....
        /// </summary>
        public static string Converting {
            get {
                return ResourceManager.GetString("Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutkitaan tiedostoja....
        /// </summary>
        public static string EvaluatingFiles {
            get {
                return ResourceManager.GetString("EvaluatingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erotetaan kirjanmerkkejä....
        /// </summary>
        public static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toiminto suoritettu!.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noudetaan kirjanmerkkejä....
        /// </summary>
        public static string GettingBookmarks {
            get {
                return ResourceManager.GetString("GettingBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yhdistetään tiedostoja....
        /// </summary>
        public static string Merging {
            get {
                return ResourceManager.GetString("Merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suoritetaan....
        /// </summary>
        public static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
    }
}
