//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFExtractor.Modules.NewBookmark.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class InputValues : global::System.Configuration.ApplicationSettingsBase {
        
        private static InputValues defaultInstance = ((InputValues)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InputValues())));
        
        public static InputValues Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Identifier {
            get {
                return ((string)(this["Identifier"]));
            }
            set {
                this["Identifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Identifier_EN {
            get {
                return ((string)(this["Identifier_EN"]));
            }
            set {
                this["Identifier_EN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Identifier_SV {
            get {
                return ((string)(this["Identifier_SV"]));
            }
            set {
                this["Identifier_SV"] = value;
            }
        }
    }
}
